server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  flyway:
    baseline-on-migrate: true
    clean-disabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: com.wutsi.platform.core.util.CustomPhysicalNamingStrategy

  datasource:
    url: "jdbc:mysql://localhost:3306/membership?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password:
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      idle-timeout: 10000 #maximum idle time for connection
      minimum-idle: 8 #minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-pool-size: 8 #maximum pool size
      maximum-pool-size: 8 #maximum pool size
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.

wutsi:
  client-id: membership-manager
  application:
    name: membership-manager
    services:
      category:
        url: https://int-wutsi.s3.amazonaws.com/static/membership-manager-server/csv/business-categories.csv
      place:
        url-prefix: https://int-wutsi.s3.amazonaws.com/static/membership-manager-server/csv
        min-population: 10000
  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    security:
      type: jwt
      api-key: "--membership-manager-api-key--"
      verify-token: false
      public-endpoints:
        - "POST /v1/members"
        - "GET /v1/members/start-registration"
    stream:
      name: ${wutsi.application.name}
      type: local
    tracing:
      client-id: ${wutsi.application.name}

logging:
  level:
    root: INFO
    com.wutsi.membership.manager: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


