spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  client-id: membership-manager
  application:
    services:
      category:
        url: https://prod-wutsi.s3.amazonaws.com/static/membership-manager-server/csv/business-categories.csv
      place:
        url-prefix: https://prod-wutsi.s3.amazonaws.com/static/membership-manager-server/csv
  platform:
    security:
      type: jwt
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

