openapi: "3.0.0"
info:
  title: "Wutsi Membership Manager API"
  description: Membership Business layer
  version: "1.0.0"

servers:
  - url: https://membership-manager-test.herokuapp.com
    description: Sandbox
  - url: https://membership-manager-prod.herokuapp.com
    description: Production

paths:
  /v1/members/search:
    post:
      operationId: "search-member"
      description: Search Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchMemberRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMemberResponse'
        409:
          description: The phone already assigned to another member
      tags:
        - Member
      security:
        - api_key: []

  /v1/members:
    get:
      operationId: "get-member"
      description: Return the current member
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMemberResponse'
        409:
          description: The phone already assigned to another member
      tags:
        - Member
      security:
        - api_key: []

    post:
      operationId: "register-member"
      description: Register a new member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterMemberRequest'
      responses:
        200:
          description: Success
      tags:
        - Member
      security:
        - api_key: []

    delete:
      operationId: "delete-member"
      description: Delete a member
      responses:
        200:
          description: Success
      tags:
        - Member
      security:
        - api_key: []

  /v1/members/attributes:
    post:
      operationId: "update-member-attribute"
      description: Update the attribute of a member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMemberAttributeRequest'
      responses:
        200:
          description: Success
      tags:
        - Member
      security:
        - api_key: []

  /v1/members/business:
    post:
      operationId: "enable-business"
      description: Enable business account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnableBusinessRequest'
      responses:
        200:
          description: Success
      tags:
        - Member

    delete:
      operationId: "disable-business"
      description: Disable business account
      responses:
        200:
          description: Success
      tags:
        - Member
      security:
        - api_key: []

  /v1/categories/import:
    get:
      operationId: "import-category"
      description: Import all the categories
      parameters:
        - in: query
          name: language
          description: 2 letter code of the language of the categories
          required: true
          schema:
            type: string
            required: true
      responses:
        200:
          description: Success
      tags:
        - Category
      security:
        - api_key: []

  /v1/places/import:
    get:
      operationId: "import-place"
      description: Import all the places
      parameters:
        - in: query
          name: country
          description: 2 letter code of the country
          required: true
          schema:
            type: string
            required: true
      responses:
        200:
          description: Success
      tags:
        - Place
      security:
        - api_key: []

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    RegisterMemberRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          description: Phone number in the [E164](https://en.wikipedia.org/wiki/E.164) format
          maxLength: 30
        displayName:
          type: string
          description: Name of the member
        country:
          type: string
          description: |
            2 letter code of the account's conntry ([ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)).
          minLength: 2
          maxLength: 2
        pin:
          type: string
          description: User's Personal Identification Number
          minLength: 4
          maxLength: 30
        cityId:
          type: integer
          format: int64
          description: ID of the location of the member
          nullable: true
      required:
        - phoneNumber
        - displayName
        - pin

    UpdateMemberAttributeRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the attribute
        value:
          type: string
          description: Value of the attribute
          nullable: true
      required:
        - name

    EnableBusinessRequest:
      type: object
      properties:
        displayName:
          type: string
          description: Account's display name
          maxLength: 50
        categoryId:
          type: number
          format: int64
          description: ID of the business category
        cityId:
          type: number
          format: int64
          description: ID of the city
        biography:
          type: string
          nullable: true
          maxLength: 160
        whatsapp:
          type: string
          description: Whatsapp phone number to use to contact the user
          nullable: true
          maxLength: 30
      required:
        - displayName
        - categoryId
        - cityId

    SearchMemberRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          description: |
            Phone number in the [E164](https://en.wikipedia.org/wiki/E.164) format
          nullable: true
        limit:
          type: integer
          default: 100
        offset:
          type: integer
          default: 0

    SearchMemberResponse:
      type: object
      properties:
        members:
          type: array
          items:
            $ref: "#/components/schemas/MemberSummary"

    MemberSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the member
        pictureUrl:
          type: string
          format: url
          description: URL of the member picture
          nullable: true
        displayName:
          type: string
          description: Display Name
        active:
          type: boolean
          description: Is the membe active
        language:
          type: string
        country:
          type: string
        cityId:
          type: integer
          format: int64
          description: ID of the city
          nullable: true
        categoryId:
          type: integer
          format: int64
          description: ID of the category - for Business Member
          nullable: true
        business:
          type: boolean
          default: false
          description: TRUE if this is a business member
        superUser:
          type: boolean
          default: false
          description: TRUE if this is a super user

    GetMemberResponse:
      type: object
      properties:
        member:
          type: object
          $ref: "#/components/schemas/Member"

    Member:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the member
        phoneNumber:
          type: string
          description: Phone number
        email:
          type: string
          format: email
          description: Email
          nullable: true
        pictureUrl:
          type: string
          format: url
          description: URL of the member picture
          nullable: true
        displayName:
          type: string
          description: Display Name
        active:
          type: boolean
          description: Is the membe active
        language:
          type: string
        country:
          type: string
        business:
          type: boolean
          default: false
          description: TRUE if this is a business member
        superUser:
          type: boolean
          default: false
          description: TRUE if this is a super user
        biography:
          type: string
          nullable: true
        website:
          type: string
          nullable: true
        whatsapp:
          type: string
          description: Whatsapp phone number to use to contact the user
          nullable: true
        street:
          type: string
          description: Street of the address
          nullable: true
        timezoneId:
          type: string
          nullable: true
          description: Timezone
        facebookId:
          type: string
          description: Facebook identifier
          nullable: true
        instagramId:
          type: string
          description: Instagram identifier
          nullable: true
        twitterId:
          type: string
          description: Twitter identifier
          nullable: true
        youtubeId:
          type: string
          description: YouTue identifier
          nullable: true
        storeId:
          type: integer
          format: int64
          description: ID of the store
          nullable: true
        businessId:
          type: integer
          format: int64
          description: ID of the account's business
          nullable: true
        city:
          type: object
          $ref: "#/components/schemas/Place"
          nullable: true
        category:
          type: object
          $ref: "#/components/schemas/Category"
          nullable: true

    Place:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Place ID
        name:
          type: string
          description: Name of the place
        longName:
          type: string
          description: Long version of the name, including city + country
        country:
          type: string
          description: Country code
        type:
          type: string
          enum:
            - CITY
            - STATE
            - COUNTRY
        longitude:
          type: number
          format: double
          nullable: true
        latitude:
          type: number
          format: double
          nullable: true
        timezoneId:
          type: string
          nullable: true

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Category title

